batch_size: 128
epsilon: 1.0
input_net_folder: nn_inputs/kuhn
learning_rate: 0.0003
lr_decay_factors:
- 1
- 3
- 8
- 20
- 50
- 100
lr_decay_steps:
- 15000
- 30000
- 50000
- 65000
- 80000
num_episodes: 100000
q_batch_size: 32
q_learning_rate: 3.0e-05
q_net_config: config/hypernet.yaml
q_replay_buffer_size: 100000
q_train_every: 5
q_weight_decay: 0
replay_buffer_size: 100000
train_every: 1
weight_decay: 0
