learning_rate: 0.001
weight_decay: 0.001
num_episodes: 10000
epsilon: 0.1
# input_net_folder: "../nn_inputs/kuhn"
input_net_folder: "../nn_inputs/rps"
replay_buffer_size: 1000
train_every: 32
batch_size: 64
