learning_rate: 0.0001
weight_decay: 0
num_episodes: 100000
# epsilon: 0.2
epsilon: 1.0
# input_net_folder: "../nn_inputs/kuhn"
input_net_folder: "../nn_inputs/kuhn-0-big"
# input_net_folder: "../nn_inputs/rps"
# replay_buffer_size: 2000
replay_buffer_size: 5000
train_every: 10
batch_size: 32
