learning_rate: 0.0001
weight_decay: 0.001
num_episodes: 30000
epsilon: 0.1
input_net_folder: "../nn_inputs/kuhn"
# input_net_folder: "../nn_inputs/rps"
replay_buffer_size: 500
train_every: 8
batch_size: 64
